onboarding = false

[theme]
name = "tokyo-night"

[keys]
prefix = "cmd+j"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"

[[keys.command]]
key = "prefix+L"
type = "popup"
command = "exec \"${SHELL|-sh}\""
width = "80%"
height = "80%"
